import { expandedWords } from '../../prisma/expanded-words'

export interface WordPackEntry {
  wordText: string
  syllableCount: number
  difficultyLevel: number
  category: string
}

type WordTuple = [wordText: string, syllableCount: number, category?: string]

function buildPack(
  entries: WordTuple[],
  difficultyLevel: number
): WordPackEntry[] {
  return entries.map(([wordText, syllableCount, category = 'noun']) => ({
    wordText,
    syllableCount,
    difficultyLevel,
    category,
  }))
}

const FRENCH_EASY: WordTuple[] = [
  ['rime', 1],
  ['flamme', 1],
  ['scene', 1],
  ['voix', 1],
  ['style', 1],
  ['beat', 1],
  ['phase', 1],
  ['pulse', 1],
  ['souffle', 1],
  ['calme', 1],
  ['pacte', 1],
  ['verbe', 1],
  ['plume', 1],
  ['trace', 1],
  ['force', 1],
  ['casque', 1],
  ['foule', 1],
  ['onde', 1],
  ['caisse', 1],
  ['clip', 1],
  ['crew', 1],
  ['clash', 1],
  ['route', 1],
  ['ville', 1],
  ['marche', 1],
  ['drame', 1],
  ['charme', 1],
  ['preuve', 1],
  ['braise', 1],
  ['front', 1],
  ['son', 1],
  ['bloc', 1],
  ['code', 1],
  ['piste', 1],
  ['blaze', 1],
  ['vibe', 1],
]

const FRENCH_MEDIUM: WordTuple[] = [
  ['energie', 3],
  ['rythme', 1],
  ['vision', 2],
  ['horizon', 3],
  ['parcours', 2],
  ['respect', 2],
  ['ambition', 3],
  ['gravite', 3],
  ['nuance', 2],
  ['courage', 2],
  ['impact', 2],
  ['memoire', 3],
  ['victoire', 3],
  ['patience', 2],
  ['alliance', 2],
  ['presence', 2],
  ['mystere', 3],
  ['lumiere', 2],
  ['confiance', 2],
  ['harmonie', 3],
  ['cadence', 2],
  ['melodie', 3],
  ['tempete', 2],
  ['racines', 2],
  ['promesse', 2],
  ['voyage', 2],
  ['balance', 2],
  ['sagesse', 2],
  ['panique', 2],
  ['mirage', 2],
  ['legende', 2],
  ['rebond', 2],
  ['tournant', 2],
  ['espoir', 2],
  ['tension', 2],
  ['nature', 2],
]

const FRENCH_HARD: WordTuple[] = [
  ['determination', 5],
  ['imagination', 5],
  ['vibration', 3],
  ['authentique', 3],
  ['transformation', 4],
  ['constellation', 4],
  ['expression', 3],
  ['revolutionnaire', 6],
  ['responsabilite', 6],
  ['perseverance', 4],
  ['illumination', 5],
  ['collaboration', 5],
  ['acceleration', 5],
  ['manifestation', 5],
  ['exploration', 4],
  ['interpretation', 5],
  ['narration', 3],
  ['celebration', 4],
  ['emancipation', 5],
  ['concentration', 4],
  ['improvisation', 5],
  ['motivation', 4],
  ['revelation', 4],
  ['respiration', 4],
  ['conversation', 4],
  ['federation', 4],
  ['inspiration', 4],
  ['architecture', 4],
  ['orientation', 4],
  ['meditation', 4],
  ['vulnerabilite', 6],
  ['singularite', 5],
  ['electricite', 5],
  ['solidarite', 4],
  ['creativite', 4],
  ['originalite', 5],
  ['legitimite', 5],
  ['sensibilite', 5],
]

const PORTUGUESE_EASY: WordTuple[] = [
  ['rima', 2],
  ['voz', 1],
  ['pulso', 2],
  ['ritmo', 2],
  ['flow', 1],
  ['chama', 2],
  ['forca', 2],
  ['rua', 2],
  ['palco', 2],
  ['verso', 2],
  ['brilho', 2],
  ['base', 2],
  ['grave', 2],
  ['sonho', 2],
  ['foco', 2],
  ['luta', 2],
  ['toque', 2],
  ['ponte', 2],
  ['trama', 2],
  ['grito', 2],
  ['marco', 2],
  ['pista', 2],
  ['bairro', 2],
  ['prova', 2],
  ['curva', 2],
  ['fogo', 2],
  ['calma', 2],
  ['tinta', 2],
  ['nevoa', 3],
  ['faixa', 2],
  ['passo', 2],
  ['queda', 2],
  ['norte', 2],
  ['linha', 2],
  ['rosto', 2],
  ['turno', 2],
]

const PORTUGUESE_MEDIUM: WordTuple[] = [
  ['energia', 4],
  ['visao', 2],
  ['caminho', 3],
  ['batida', 3],
  ['proposito', 4],
  ['atitude', 3],
  ['respeito', 3],
  ['coragem', 3],
  ['memoria', 4],
  ['vitoria', 4],
  ['paciencia', 4],
  ['firmeza', 3],
  ['clareza', 3],
  ['balanco', 3],
  ['cadencia', 4],
  ['sintonia', 4],
  ['destino', 3],
  ['verdade', 3],
  ['cultura', 3],
  ['legenda', 3],
  ['progresso', 3],
  ['misterio', 4],
  ['harmonia', 4],
  ['confianca', 4],
  ['presenca', 3],
  ['unidade', 4],
  ['viagem', 3],
  ['mensagem', 3],
  ['impulso', 3],
  ['projeto', 3],
  ['palavra', 3],
  ['justica', 3],
  ['deslize', 3],
  ['virtude', 3],
  ['ternura', 3],
  ['mistura', 3],
]

const PORTUGUESE_HARD: WordTuple[] = [
  ['determinacao', 5],
  ['transformacao', 4],
  ['autenticidade', 6],
  ['oportunidade', 6],
  ['constelacao', 4],
  ['manifestacao', 5],
  ['imaginacao', 5],
  ['revolucionario', 6],
  ['responsabilidade', 7],
  ['perseveranca', 5],
  ['colaboracao', 5],
  ['aceleracao', 5],
  ['improvisacao', 5],
  ['concentracao', 5],
  ['inspiracao', 4],
  ['meditacao', 4],
  ['eletricidade', 6],
  ['singularidade', 6],
  ['criatividade', 5],
  ['originalidade', 6],
  ['vulnerabilidade', 6],
  ['multiplicidade', 6],
  ['ancestralidade', 5],
  ['possibilidade', 6],
  ['continuidade', 5],
  ['sensibilidade', 6],
  ['intensidade', 4],
  ['finalidade', 5],
  ['comunidade', 5],
  ['diversidade', 5],
  ['representacao', 5],
  ['comunicacao', 5],
  ['legitimidade', 6],
  ['profundidade', 5],
  ['espiritualidade', 7],
  ['velocidade', 5],
  ['musicalidade', 6],
  ['ancestralismo', 5],
]

export const ENGLISH_WORD_PACK: WordPackEntry[] = expandedWords.map((word) => ({
  wordText: word.wordText,
  syllableCount: word.syllableCount,
  difficultyLevel: word.difficultyLevel,
  category: word.category,
}))

export const FRENCH_WORD_PACK: WordPackEntry[] = [
  ...buildPack(FRENCH_EASY, 1),
  ...buildPack(FRENCH_MEDIUM, 2),
  ...buildPack(FRENCH_HARD, 3),
]

export const PORTUGUESE_WORD_PACK: WordPackEntry[] = [
  ...buildPack(PORTUGUESE_EASY, 1),
  ...buildPack(PORTUGUESE_MEDIUM, 2),
  ...buildPack(PORTUGUESE_HARD, 3),
]
