export const ACHIEVEMENTS = [
  // Session Milestones
  {
    code: 'FIRST_FLOW',
    name: 'First Flow',
    description: 'Completed your first freestyle session.',
    icon: 'Mic',
    points: 10,
    target: 1,
    progressType: 'sessions',
  },
  {
    code: 'SESSION_5',
    name: 'Getting Started',
    description: 'Completed 5 sessions.',
    icon: 'Play',
    points: 25,
    target: 5,
    progressType: 'sessions',
  },
  {
    code: 'SESSION_20',
    name: 'Dedicated',
    description: 'Completed 20 sessions.',
    icon: 'TrendingUp',
    points: 50,
    target: 20,
    progressType: 'sessions',
  },
  {
    code: 'SESSION_50',
    name: 'Studio Rat',
    description: 'Completed 50 sessions.',
    icon: 'Headphones',
    points: 100,
    target: 50,
    progressType: 'sessions',
  },
  {
    code: 'SESSION_100',
    name: 'Freestyla Legend',
    description: 'Completed 100 sessions.',
    icon: 'Crown',
    points: 500,
    target: 100,
    progressType: 'sessions',
  },

  // Recording Milestones
  {
    code: 'FIRST_RECORDING',
    name: 'Mic Check',
    description: 'Saved your first recording.',
    icon: 'CassetteTape',
    points: 15,
    target: 1,
    progressType: 'recordings',
  },
  {
    code: 'RECORDING_10',
    name: 'Tape Deck',
    description: 'Saved 10 recordings.',
    icon: 'Library',
    points: 50,
    target: 10,
    progressType: 'recordings',
  },
  {
    code: 'RECORDING_50',
    name: 'Album Ready',
    description: 'Saved 50 recordings.',
    icon: 'Disc',
    points: 200,
    target: 50,
    progressType: 'recordings',
  },

  // Streaks
  {
    code: 'STREAK_3',
    name: 'Heating Up',
    description: 'Practiced for 3 days in a row.',
    icon: 'Flame',
    points: 50,
    target: 3,
    progressType: 'streak',
  },
  {
    code: 'STREAK_7',
    name: 'On Fire',
    description: 'Practiced for 7 days in a row.',
    icon: 'Zap',
    points: 100,
    target: 7,
    progressType: 'streak',
  },
  {
    code: 'STREAK_30',
    name: 'Unstoppable',
    description: 'Practiced for 30 days in a row.',
    icon: 'Trophy',
    points: 500,
    target: 30,
    progressType: 'streak',
  },

  // Beat Exploration
  {
    code: 'BEAT_EXPLORER_5',
    name: 'Vibe Checker',
    description: 'Practiced on 5 different beats.',
    icon: 'Music',
    points: 30,
    target: 5,
    progressType: 'beats',
  },
  {
    code: 'BEAT_MASTER_20',
    name: 'Crate Digger',
    description: 'Practiced on 20 different beats.',
    icon: 'Disc3',
    points: 100,
    target: 20,
    progressType: 'beats',
  },

  // Word Vault
  {
    code: 'WORDS_50',
    name: 'Word Smith',
    description: 'Collected 50 unique words.',
    icon: 'Book',
    points: 50,
    target: 50,
    progressType: 'words',
  },
  {
    code: 'WORDS_200',
    name: 'Lyricist',
    description: 'Collected 200 unique words.',
    icon: 'Feather',
    points: 150,
    target: 200,
    progressType: 'words',
  },
  {
    code: 'WORDS_1000',
    name: 'Vocabulary God',
    description: 'Collected 1000 unique words.',
    icon: 'Scroll',
    points: 1000,
    target: 1000,
    progressType: 'words',
  },

  // Time Based (no progress tracking - one-time conditions)
  {
    code: 'EARLY_BIRD',
    name: 'Early Bird',
    description: 'Completed a session before 8 AM.',
    icon: 'Sun',
    points: 20,
  },
  {
    code: 'NIGHT_OWL',
    name: 'Night Owl',
    description: 'Completed a session after 11 PM.',
    icon: 'Moon',
    points: 20,
  },
  {
    code: 'WEEKEND_WARRIOR',
    name: 'Weekend Warrior',
    description: 'Completed sessions on both Saturday and Sunday.',
    icon: 'Calendar',
    points: 30,
  },
  // --- WAVE 2: CAREER UPDATE ---

  // XP & Progression
  {
    code: 'LEVEL_5',
    name: 'Rising Star',
    description: 'Reached Level 5.',
    icon: 'TrendingUp',
    points: 50,
    target: 5,
    progressType: 'level',
  },
  {
    code: 'LEVEL_10',
    name: 'Headliner',
    description: 'Reached Level 10.',
    icon: 'Star',
    points: 100,
    target: 10,
    progressType: 'level',
  },
  {
    code: 'LEVEL_25',
    name: 'Icon',
    description: 'Reached Level 25.',
    icon: 'Award',
    points: 250,
    target: 25,
    progressType: 'level',
  },
  {
    code: 'LEVEL_50',
    name: 'Living Legend',
    description: 'Reached Level 50.',
    icon: 'Crown',
    points: 1000,
    target: 50,
    progressType: 'level',
  },
  {
    code: 'XP_10K',
    name: 'Paid Dues',
    description: 'Earned 10,000 Total XP.',
    icon: 'Briefcase',
    points: 100,
    target: 10000,
    progressType: 'xp',
  },
  {
    code: 'XP_100K',
    name: 'Six Figures',
    description: 'Earned 100,000 Total XP.',
    icon: 'Diamond',
    points: 500,
    target: 100000,
    progressType: 'xp',
  },

  // Streaks & Consistency
  {
    code: 'STREAK_14',
    name: 'Fortnight Flow',
    description: 'Practiced for 14 days in a row.',
    icon: 'CalendarCheck',
    points: 200,
    target: 14,
    progressType: 'streak',
  },
  {
    code: 'STREAK_60',
    name: 'Habit Former',
    description: 'Practiced for 60 days in a row.',
    icon: 'Link',
    points: 400,
    target: 60,
    progressType: 'streak',
  },
  {
    code: 'STREAK_100',
    name: 'Century Club',
    description: 'Practiced for 100 days in a row.',
    icon: 'Infinity',
    points: 1000,
    target: 100,
    progressType: 'streak',
  },
  {
    code: 'STREAK_365',
    name: 'Year of Flow',
    description: 'Practiced for 365 days in a row.',
    icon: 'Globe',
    points: 5000,
    target: 365,
    progressType: 'streak',
  },
  {
    code: 'COMEBACK',
    name: 'The Remix',
    description: 'Returned after 7 days of inactivity.',
    icon: 'RotateCcw',
    points: 50,
  },

  // Skill & Flow Density
  {
    code: 'SPITFIRE',
    name: 'Spitfire',
    description: 'Spit over 150 words in a single session.',
    icon: 'Flame',
    points: 50,
  },
  {
    code: 'RAP_GOD',
    name: 'Rap Deity',
    description: 'Spit over 300 words in a single session.',
    icon: 'Zap',
    points: 150,
  },
  {
    code: 'MARATHON',
    name: 'Iron Lungs',
    description: 'Completed a session longer than 5 minutes.',
    icon: 'Activity',
    points: 75,
  },
  {
    code: 'ONE_TAKE',
    name: 'One Take Wonder',
    description: 'Completed a session with 0 restarts.',
    icon: 'CheckCircle',
    points: 50,
  },
  {
    code: 'SLOW_FLOW',
    name: 'Pocket Watcher',
    description: 'Completed a session on 4-Bar Frequency.',
    icon: 'Anchor',
    points: 30,
  },
  {
    code: 'DOUBLE_TIME',
    name: 'Double Time',
    description: 'Completed a session on 16-Bar Frequency.',
    icon: 'ChevronsRight',
    points: 30,
  },

  // Volume & Dedication
  {
    code: 'TIME_1H',
    name: 'Studio Rat',
    description: 'Accumulated 1 hour of total playtime.',
    icon: 'Clock',
    points: 50,
    target: 60,
    progressType: 'minutes',
  },
  {
    code: 'TIME_10H',
    name: 'Mixtape Ready',
    description: 'Accumulated 10 hours of total playtime.',
    icon: 'HardDrive',
    points: 200,
    target: 600,
    progressType: 'minutes',
  },
  {
    code: 'TIME_24H',
    name: 'Day One Flow',
    description: 'Accumulated 24 hours of total playtime.',
    icon: 'Sun',
    points: 500,
    target: 1440,
    progressType: 'minutes',
  },
  {
    code: 'TOTAL_WORDS_5K',
    name: 'Novelist',
    description: 'Collected 5,000 total words.',
    icon: 'BookOpen',
    points: 300,
    target: 5000,
    progressType: 'words',
  },

  // Exploration & Social
  {
    code: 'GENRE_3',
    name: 'Versatile',
    description: 'Practiced on 3 different genres.',
    icon: 'Layers',
    points: 50,
    target: 3,
    progressType: 'genres',
  },
  {
    code: 'GENRE_ALL',
    name: 'Master of All',
    description: 'Practiced on all available genres.',
    icon: 'Box',
    points: 200,
  },
  {
    code: 'CYPHER_1',
    name: 'Pass the Mic',
    description: 'Completed your first Cypher session.',
    icon: 'Users',
    points: 50,
    target: 1,
    progressType: 'cyphers',
  },
  {
    code: 'CYPHER_10',
    name: 'Crew Love',
    description: 'Completed 10 Cypher sessions.',
    icon: 'Heart',
    points: 150,
    target: 10,
    progressType: 'cyphers',
  },
  {
    code: 'CYPHER_50',
    name: 'Battle Tested',
    description: 'Completed 50 Cypher sessions.',
    icon: 'Swords',
    points: 500,
    target: 50,
    progressType: 'cyphers',
  },

  // Context
  {
    code: 'LUNCH_BREAK',
    name: 'Lunch Money',
    description: 'Completed a session between 12PM and 2PM.',
    icon: 'Coffee',
    points: 20,
  },
  {
    code: 'MIDNIGHT',
    name: 'Midnight Marauder',
    description: 'Completed a session between 12AM and 3AM.',
    icon: 'Moon',
    points: 30,
  },
]

// Type for progress calculation
export type ProgressType =
  | 'sessions'
  | 'recordings'
  | 'beats'
  | 'streak'
  | 'words'
  | 'level'
  | 'xp'
  | 'minutes'
  | 'genres'
  | 'cyphers'
